import turtle as t

t.shape('turtle')
def draw_circle(r):
    k = 40
    for j in range(k):
        t.forward(r)
        t.left(360 / k)
def draw_halfcircle(r):
    k = 40
    for j in range(k):
        t.forward(r)
        t.left(180 / k)
def moove(x,y):
    t.penup()
    t.goto(x,y)
    t.pendown()
t.speed(0)
moove(0,-100)
t.begin_fill()
t.color('green')
draw_circle(25)
t.end_fill()
moove(-170,170)
t.begin_fill()
draw_circle(5)
t.end_fill()
t.begin_fill()
t.goto(-100,140)
t.goto(-140,210)
t.end_fill()
moove(190,170)
t.begin_fill()
draw_circle(5)
t.end_fill()
t.begin_fill()
t.goto(100,140)
t.goto(180,230)
t.end_fill()
moove(-170,185)
t.begin_fill()
t.color('oliveDrab4')
draw_circle(3)
t.end_fill()
moove(195,185)
t.begin_fill()
draw_circle(3)
t.end_fill()
moove(10,50)
t.width(20)
t.color('oliveDrab4')
t.goto(10,20)
moove(-50,70)
t.begin_fill()
t.color('white')
draw_circle(5)
t.end_fill()
moove(70,70)
t.begin_fill()
draw_circle(5)
t.end_fill()
moove(-48,80)
t.begin_fill()
t.color('red')
draw_circle(3)
t.end_fill()
moove(72,80)
t.begin_fill()
t.color('red')
draw_circle(3)
t.end_fill()
moove(-70,5)
t.right(90)
t.begin_fill()
draw_halfcircle(6)
t.end_fill()
moove(900,1000)
t.exitonclick()

